import pytest
import os

def test_main_outputs():
    # Test that the main function produces expected outputs
    from main import main
    
    main()
    
    # List of expected files from the analysis directory
    analysis_files = [
        "analysis/ASF_analysis_comparison.png",
        "analysis/ASF_group_comparison.csv",
        "analysis/eTIV_analysis_comparison.png",
        "analysis/eTIV_group_comparison.csv",
        "analysis/nWBV_analysis_comparison.png",
        "analysis/nWBV_group_comparison.csv"
    ]
    
    # List of expected files from the plots directory
    plot_files = [
        "plots/ASF_boxplot.png",
        "plots/ASF_kde.png",
        "plots/eTIV_boxplot.png",
        "plots/eTIV_kde.png",
        "plots/nWBV_boxplot.png",
        "plots/nWBV_kde.png"
    ]
    
    # Original expected file
    data_files = ["data/cleaned_dataset.csv"]
    
    # Combine all expected files
    expected_files = analysis_files + plot_files + data_files
    
    # Check each file exists
    for file_path in expected_files:
        assert os.path.exists(
            file_path
        ), f"{file_path} should be generated by main"
        
    # Additional check to verify number of files
    assert len(expected_files) == 13, "Expected 13 output files to be generated"