import pytest
import os


def test_main_outputs():
    # Test that the main function produces expected outputs
    from main import main

    main()
    expected_files = "data/cleaned_dataset.csv"

    assert os.path.exists(
        expected_files
    ), f"{expected_files} should be generated by main"
